settings:
  chroma:
    # Local persistent client config
    type: "local"
    persist_directory": "./vector_store"
    # Remote client config
    # type: "remote"
    # uri: "<chroma_server_uri>"

    # The embedding model to use.
    embedding_model: "multi-qa-MiniLM-L6-cos-v1"
  ollama:
    host: "locahost"
    #api_key: <your API key"
    model: "llama3.2:latest"

  data_directory: "./data"