name: CI

on:
  push:
    branches: [ master, develop ]
  workflow_dispatch: # enables gh workflow run
  pull_request:
    branches: [ master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      UV_LINK_MODE: copy # fixes namespace collisions to to symlinks in bazel sandbox
    steps:
      - name: Free Disk Space (Ubuntu)
        run: |
          echo "=== Disk space before cleanup ==="
          df -h
          
          # Remove massive frameworks completely unrelated to your Python app
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/julia*
          
          # Clean Docker structures to reclaim another few gigabytes
          sudo docker image prune --all --force
          sudo docker builder prune -a --force
          
          echo "=== Disk space after cleanup ==="
          df -h


      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install uv and Python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          python-version: "3.12"
          enable-cache: true
          ignore-nothing-to-cache: true
      
      - name: Checking formatting
        run: bazel run //tools/format:format.check

      - name: Build and Run Audits (Linting/Security/Docs)
        run: |
          bazel build --config=lint //... \
            --experimental_repository_cache_hardlinks \
            --discard_analysis_cache \
            --nolegacy_important_outputs \
            

      - name: Run Unit Tests
        run: |
          bazel test --test_output=streamed //... \
            --experimental_repository_cache_hardlinks \
            --discard_analysis_cache \
            --nolegacy_important_outputs


